#!/usr/bin/env python3
"""Derive the cumulative Vulkan core requirement set for the declared target.

The declared target is **Vulkan 1.4 core for a graphics implementation**. Its
requirement set comes from two pinned primary sources, not from a roadmap
profile:

1. The pinned specification, section "Feature Requirements"
   (anchor ``features-requirements``), which states that all Vulkan graphics
   implementations must support specific features per core version, including
   the conditional ones ("X must be supported if Y is supported") and the
   "at least one of" alternatives. This is the normative source for feature
   bits, and it is what the CTS ``dEQP-VK.info.device_mandatory_features`` case
   is built to enforce.
2. The pinned registry ``vk.xml``, whose per-version ``<feature>`` blocks list
   the commands, types and enums each core version requires. This is the
   normative source for the API surface.

The roadmap profiles are deliberately *not* consulted here; they are a separate
comparison, generated by ``derive_roadmap_comparison.py``.

Both inputs are hash-verified against ``sources.json`` before parsing, so a
moving specification page or a stale registry checkout is a hard failure.

Usage
-----
    python3 conformance_inventory/tools/derive_core_target.py
    python3 conformance_inventory/tools/derive_core_target.py \
        --spec-html /path/to/vkspec.html --vk-xml /path/to/vk.xml
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
INVENTORY_DIR = os.path.dirname(HERE)
DEFAULT_SOURCES = os.path.join(INVENTORY_DIR, "sources.json")
DEFAULT_OUT = os.path.join(INVENTORY_DIR, "core_target.json")

SPEC_SOURCE_ID = "khronos-vulkan-spec"
REGISTRY_SOURCE_ID = "khronos-vulkan-registry"
SECTION_START = 'id="features-requirements"'
TAG_RE = re.compile(r"<(/?)ul>|<(/?)li>")
ANCHOR_FEATURE_RE = re.compile(r'href="#features-([A-Za-z0-9_]+)"')
ANCHOR_EXT_RE = re.compile(r'href="#(VK_[A-Za-z0-9_]+)"')
STRIP_RE = re.compile(r"<[^>]+>")
VERSION_RE = re.compile(r"If Vulkan (1\.[0-9]) is supported")


def log(message: str) -> None:
    print(message, file=sys.stderr)


def load_sources(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def find_source(sources: dict, source_id: str) -> dict:
    for source in sources.get("sources", []):
        if source.get("id") == source_id:
            return source
    raise SystemExit("sources.json has no %s entry" % source_id)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "ps5vk-cis-core-target"})
    with urllib.request.urlopen(request, timeout=180) as response:
        return response.read()


def read_input(local: str | None, url: str, expected_sha256: str, label: str) -> bytes:
    if local:
        with open(local, "rb") as handle:
            data = handle.read()
        origin = local
    else:
        data = fetch(url)
        origin = url
    digest = hashlib.sha256(data).hexdigest()
    if digest != expected_sha256:
        raise SystemExit(
            "stale/incompatible %s pin: %s has sha256 %s, sources.json records %s" % (label, origin, digest, expected_sha256)
        )
    return data


def clean(html_fragment: str) -> str:
    text = STRIP_RE.sub(" ", html_fragment)
    text = text.replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&").replace("&#8217;", "'")
    return re.sub(r"\s+", " ", text).strip()


def list_items(fragment: str, depth: int) -> list[str]:
    """Return the <li> fragments that sit directly inside the list at `depth`."""
    items: list[str] = []
    current = 0
    start = None
    for match in TAG_RE.finditer(fragment):
        tag = match.group(0)
        if tag == "<ul>":
            current += 1
        elif tag == "</ul>":
            current -= 1
        elif tag == "<li>":
            if current == depth:
                start = match.end()
        elif tag == "</li>":
            if current == depth and start is not None:
                items.append(fragment[start:match.start()])
                start = None
    return items


def parse_trigger(text: str) -> dict | None:
    """Parse an "if ..." clause into an explicit condition tree.

    Kinds: feature, extension, not, any-of, all-of, text. Negations and
    alternatives stay explicit; they are never flattened into a plain string.
    """
    clause = text.strip()
    if clause.lower().startswith("if "):
        clause = clause[3:].strip()
    clause = clause.strip(" .,")
    if not clause:
        return None
    if clause.lower().endswith("is not advertised"):
        name = clause[: -len("is not advertised")].strip().strip(",")
        return {"kind": "not", "operand": {"kind": "extension", "name": name, "state": "advertised"}}
    clause = re.sub(r"\s+(is|are)\s+supported$", "", clause).strip()
    clause = re.sub(r"\s+is supported$", "", clause).strip()
    parts = [part.strip() for part in re.split(r",|\bor\b", clause) if part.strip()]
    operands = []
    for part in parts:
        part = re.sub(r"^the\s+", "", part).strip()
        part = re.sub(r"\s+feature$", "", part).strip().strip("`* ")
        if part:
            operands.append({"kind": "extension" if part.startswith("VK_") else "feature", "name": part})
    if not operands:
        return {"kind": "text", "text": clause}
    if len(operands) == 1:
        return operands[0]
    return {"kind": "any-of", "operands": operands}


def condition_explanation(condition: dict | None) -> str:
    if condition is None:
        return ""
    kind = condition.get("kind")
    if kind == "feature":
        return "when feature %s is supported" % condition["name"]
    if kind == "extension":
        return "when extension %s is supported" % condition["name"]
    if kind == "not":
        return "unless %s is advertised" % condition["operand"].get("name")
    if kind == "any-of":
        return "when any of these holds: " + ", ".join(condition_explanation(part) or part.get("name", "") for part in condition["operands"])
    if kind == "all-of":
        return "when all of these hold: " + ", ".join(condition_explanation(part) or part.get("name", "") for part in condition["operands"])
    return condition.get("text", "")


def parse_requirement(fragment: str) -> dict | None:
    """Return {"kind": feature|any-of, "features": [...]} for a requirement clause."""
    text = clean(fragment)
    features = ANCHOR_FEATURE_RE.findall(fragment)
    if not features:
        return None
    if "at least one" in text.lower() and len(features) > 1:
        return {"kind": "any-of", "features": features}
    return {"kind": "feature", "features": [features[0]]}


def parse_entry(fragment: str) -> list[dict]:
    """Parse one requirement entry, preserving any-of semantics.

    A single entry is returned per clause. "at least one of A, B or C" stays one
    any-of obligation instead of becoming three simultaneous requirements.
    """
    text = clean(fragment)
    nested = list_items(fragment, 1)
    if nested and "following features" in text.lower():
        trigger = parse_trigger(text.split("must be supported")[0])
        items = []
        for child in nested:
            items.extend(parse_entry(child))
        if not items:
            return []
        return [
            {
                "requirement": {"kind": "all-of", "items": [item["requirement"] for item in items]},
                "features": sorted({name for item in items for name in item["features"]}),
                "condition": items[0]["condition"],
                "trigger": trigger,
                "at_least_one": False,
                "text": text,
                "explanation": "All of the listed feature obligations apply" + ((" " + condition_explanation(trigger)) if trigger else ""),
            }
        ]
    if " if " in text:
        head, _, tail = text.partition(" if ")
        requirement = parse_requirement(fragment)
        if requirement is not None:
            head_features = [name for name in requirement["features"] if name in head]
            if head_features:
                requirement["features"] = head_features
            elif requirement["kind"] == "any-of":
                requirement = {"kind": "feature", "features": [requirement["features"][0]]}
        trigger = parse_trigger(tail)
        condition = tail.strip()
    else:
        requirement = parse_requirement(fragment)
        trigger = None
        condition = None
    if requirement is None:
        return []
    explanation = (
        ("At least one of these features must be supported" if requirement["kind"] == "any-of" else "This feature must be supported")
        + ((" " + condition_explanation(trigger)) if trigger else "")
    )
    return [
        {
            "requirement": requirement,
            "features": list(requirement["features"]),
            "condition": condition,
            "trigger": trigger,
            "at_least_one": requirement["kind"] == "any-of",
            "text": text,
            "explanation": explanation,
        }
    ]


def parse_feature_requirements(html: str) -> dict:
    start = html.find(SECTION_START)
    if start < 0:
        raise SystemExit("pinned specification has no %s anchor" % SECTION_START)
    candidates = [position for position in (html.find("<h3 id=", start + 10), html.find("<h2 id=", start + 10)) if position >= 0]
    end = min(candidates) if candidates else -1
    if end < 0:
        raise SystemExit("could not find the end of the feature-requirements section")
    section = html[start:end]
    if len(section) < 2000:
        raise SystemExit("feature-requirements section looks truncated (%d bytes)" % len(section))

    by_version: dict[str, list[dict]] = {}
    conditional_features: list[dict] = []
    at_least_one: list[dict] = []
    unclassified: list[str] = []
    for item in list_items(section, 1):
        text = clean(item)
        version_match = VERSION_RE.search(text)
        if version_match and "<ul>" in item:
            version = version_match.group(1)
            entries = []
            for nested in list_items(item, 1):
                entries.extend(parse_entry(nested))
            by_version[version] = entries
            continue
        if text.lower().startswith("if ") and ANCHOR_EXT_RE.search(item):
            parsed = parse_entry(item)
            if not parsed:
                continue
            entry = parsed[0]
            entry["extensions"] = sorted({name for name in ANCHOR_EXT_RE.findall(item) if name not in entry["features"]})
            conditional_features.append(entry)
            continue
        entries = parse_entry(item)
        if entries:
            if entries[0]["at_least_one"]:
                at_least_one.extend(entries)
            else:
                unclassified.extend(entry["text"] for entry in entries)
    return {
        "by_version": by_version,
        "conditional_features": conditional_features,
        "at_least_one": at_least_one,
        "unclassified": unclassified,
        "section_bytes": len(section),
    }


def parse_vk_xml(xml_text: str) -> dict:
    import xml.etree.ElementTree as ET

    root = ET.fromstring(xml_text)
    version_features: dict[str, list[str]] = {}
    profile_surface: dict[str, dict[str, dict[str, list[str]]]] = {}
    depends: dict[str, str | None] = {}
    for feature in root.findall("feature"):
        name = feature.get("name") or ""
        version_match = re.match(r"VK_VERSION_(1_[0-9])$", name)
        profile_match = re.match(r"VK_(BASE|COMPUTE|GRAPHICS)_VERSION_(1_[0-9])$", name)
        if not version_match and not profile_match:
            continue
        depends[name] = feature.get("depends")
        parts = (version_match or profile_match).group(0).split("_")[-2:]
        version = "%s.%s" % (parts[0], parts[1])
        bucket = {"commands": set(), "types": set(), "enums": set(), "features": set()}
        for require in feature.findall("require"):
            for child in require:
                entry_name = child.get("name")
                if not entry_name:
                    continue
                if child.tag == "command":
                    bucket["commands"].add(entry_name)
                elif child.tag == "type":
                    bucket["types"].add(entry_name)
                elif child.tag == "enum":
                    bucket["enums"].add(entry_name)
                elif child.tag == "feature":
                    bucket["features"].add(entry_name)
        if version_match:
            version_features[version] = sorted(bucket["features"])
        else:
            profile = profile_match.group(1).lower()
            profile_surface.setdefault(profile, {})[version] = {
                "commands": sorted(bucket["commands"]),
                "types": sorted(bucket["types"]),
                "enums": sorted(bucket["enums"]),
            }

    versions = {value for surface in profile_surface.values() for value in surface} | set(version_features)
    versions = sorted(versions, key=lambda value: tuple(int(part) for part in value.split(".")))

    def cumulative(profile: str) -> dict:
        acc = {"commands": set(), "types": set(), "enums": set()}
        by_version = {}
        for version in versions:
            entry = profile_surface.get(profile, {}).get(version)
            if entry:
                for key in acc:
                    acc[key].update(entry[key])
            by_version[version] = {
                "commands": entry["commands"] if entry else [],
                "types": entry["types"] if entry else [],
                "enums_count": len(entry["enums"]) if entry else 0,
                "enums_sha1": hashlib.sha1("\n".join(entry["enums"]).encode("utf-8")).hexdigest() if entry else None,
                "cumulative_commands_count": len(acc["commands"]),
                "cumulative_types_count": len(acc["types"]),
            }
        return {
            "by_version": by_version,
            "cumulative": {
                "commands": sorted(acc["commands"]),
                "types": sorted(acc["types"]),
                "enums_count": len(acc["enums"]),
                "enums_sha1": hashlib.sha1("\n".join(sorted(acc["enums"])).encode("utf-8")).hexdigest(),
            },
        }

    graphics = cumulative("graphics")
    base = cumulative("base")
    compute = cumulative("compute")

    def dependencies_of(name: str) -> list[str]:
        declared = depends.get(name)
        if declared:
            return [part.strip() for part in re.split(r"[,+]", declared) if part.strip()]
        # The 1.x graphics/compute blocks do not always repeat `depends`; fall
        # back to the versioned chain the registry uses elsewhere.
        match = re.match(r"VK_(GRAPHICS|COMPUTE|BASE)_VERSION_(1_[0-9])$", name)
        if not match:
            return []
        family, version = match.group(1), match.group(2)
        if family == "GRAPHICS":
            return ["VK_COMPUTE_VERSION_%s" % version]
        if family == "COMPUTE":
            return ["VK_BASE_VERSION_%s" % version]
        return []

    def resolve(root_name: str) -> dict:
        seen: list[str] = []
        pending = [root_name]
        while pending:
            name = pending.pop(0)
            if name in seen:
                continue
            seen.append(name)
            for dependency in dependencies_of(name):
                if dependency not in seen:
                    pending.append(dependency)
        commands: set[str] = set()
        types: set[str] = set()
        enums: set[str] = set()
        for name in seen:
            family_match = re.match(r"VK_(GRAPHICS|COMPUTE|BASE)_VERSION_(1_[0-9])$", name)
            if not family_match:
                continue
            entry = profile_surface.get(family_match.group(1).lower(), {}).get(family_match.group(2).replace("_", "."))
            if not entry:
                continue
            commands.update(entry["commands"])
            types.update(entry["types"])
            enums.update(entry["enums"])
        return {
            "roots": seen,
            "commands": sorted(commands),
            "types": sorted(types),
            "enums": sorted(enums),
            "commands_total": len(commands),
            "types_total": len(types),
        }

    graphics_resolved = resolve("VK_GRAPHICS_VERSION_1_4")
    return {
        "versions": versions,
        "mandatory_feature_bits_by_version": version_features,
        "surface_by_profile": {
            "graphics": graphics,
            "base": base,
            "compute": compute,
            "graphics_resolved": {
                "resolution_rule": "transitive walk of the registry `depends` chain (graphics -> compute -> base) per core version, not a manual sum of categories",
                "roots": graphics_resolved["roots"],
                "commands": graphics_resolved["commands"],
                "types": graphics_resolved["types"],
                "enums_count": len(graphics_resolved["enums"]),
                "commands_total": graphics_resolved["commands_total"],
                "types_total": graphics_resolved["types_total"],
            },
            "graphics_including_base": {
                "commands_total": graphics_resolved["commands_total"],
                "types_total": graphics_resolved["types_total"],
                "commands": graphics_resolved["commands"],
                "types": graphics_resolved["types"],
            },
        },
    }


def adoc_table_block(text: str, anchor: str) -> str:
    start = text.find("[[%s]]" % anchor)
    if start < 0:
        raise SystemExit("pinned specification has no %s table" % anchor)
    open_at = text.find("|====", start)
    close_at = text.find("|====", open_at + 5)
    if open_at < 0 or close_at < 0:
        raise SystemExit("could not bound the %s table" % anchor)
    return text[open_at + 5:close_at]


FOOTNOTE_RE = re.compile(r"(?<=[\s)])\s*\^\d+\^\s*")  # footnote markers only, never the exponent of 2^30^
VALUE_TAGS_RE = re.compile(r"(?P<value>\([^()]*\)|[^(){}]+?)(?:\s*\^\d+\^)?\s*\((?P<tags>[^()]*\{[^()]*)\)")
NUMBER_RE = re.compile(r"-?\d+(?:\.\d+)?")
ULP_RE = re.compile(r"^(?P<head>.+?)\s*-\s*\(?\s*\d*\s*ULP\s*\)?$")
ENUM_PREFIXES = ("ename:", "code:", "flagname:", "apiext:")
REFERENCE_PREFIX = "pname:"
REFERENCE_PREFIX_RE = re.compile(r"(?:pname|ptext|sname|sname|fname|flink|slink|basetype):")
TAG_RE_SPLIT = re.compile(r"[,\s]+")

import ast as _ast
import operator as _operator

_ARITHMETIC_OPS = {
    _ast.Add: _operator.add,
    _ast.Sub: _operator.sub,
    _ast.Mult: _operator.mul,
    _ast.Div: _operator.truediv,
    _ast.Pow: _operator.pow,
}
POWER_RE = re.compile(r"(\d+)\^(\d+)\^?")


def _safe_arithmetic(node):
    if isinstance(node, _ast.Expression):
        return _safe_arithmetic(node.body)
    if isinstance(node, _ast.Constant) and isinstance(node.value, (int, float)):
        return node.value
    if isinstance(node, _ast.UnaryOp) and isinstance(node.op, (_ast.UAdd, _ast.USub)):
        value = _safe_arithmetic(node.operand)
        return value if isinstance(node.op, _ast.UAdd) else -value
    if isinstance(node, _ast.BinOp) and type(node.op) in _ARITHMETIC_OPS:
        return _ARITHMETIC_OPS[type(node.op)](_safe_arithmetic(node.left), _safe_arithmetic(node.right))
    raise ValueError("unsupported arithmetic")


def evaluate_arithmetic(text: str):
    """Evaluate a numeric expression after turning a^b^ powers into (a**b).

    Returns int/float, or None when the expression is not pure arithmetic.
    """
    expression = POWER_RE.sub(r"(\1**\2)", text)
    if not re.fullmatch(r"[0-9+\-*/(). ^]*", expression):
        return None
    try:
        value = _safe_arithmetic(_ast.parse(expression, mode="eval"))
    except Exception:
        return None
    if isinstance(value, (int, float)):
        return value
    return None





def interpret_number(text: str):
    """Interpret one numeric token, or return ("unknown", None)."""
    token = text.strip()
    if token in ("", "-"):
        return "none", None
    power = re.fullmatch(r"(\d+)\^(\d+)\^", token)
    if power:
        return "power", int(power.group(1)) ** int(power.group(2))
    fraction = re.fullmatch(r"(\d+)\s*/\s*(\d+)", token)
    if fraction:
        return "fraction", int(fraction.group(1)) / int(fraction.group(2))
    if re.fullmatch(r"-?\d+", token):
        return "integer", int(token)
    if re.fullmatch(r"-?\d+\.\d+", token):
        return "decimal", float(token)
    return "unknown", None


DESCRIPTIVE_VALUES = {
    "duration": "descriptive",
    "exact": "descriptive",
    "bitfield": "bitfield",
    "implementation-dependent": "descriptive",
    "recommendation": "descriptive",
    "unspecified": "descriptive",
    "false": "boolean",
    "true": "boolean",
}
FUNCTION_RE = re.compile(r"(?P<name>max|min)\s*\(")
ULP_SUFFIX_RE = re.compile(r"^(?P<head>.+?)\s*-\s*\(?\s*\d*\s*ULP\s*\)?$")


def _split_top_level(text: str, separator: str = ",") -> list[str]:
    parts, depth, current = [], 0, ""
    for char in text:
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
        if char == separator and depth == 0:
            parts.append(current.strip())
            current = ""
        else:
            current += char
    if current.strip():
        parts.append(current.strip())
    return parts


def _expression_operands(text: str) -> list[dict]:
    """Tokenize an arithmetic expression into numbers, references and functions."""
    operands, index = [], 0
    while index < len(text):
        char = text[index]
        if char.isspace() or char in "+-*/":
            operands.append({"kind": "operator", "value": char})
            index += 1
            continue
        function = FUNCTION_RE.match(text, index)
        if function:
            depth, cursor = 1, function.end()
            while cursor < len(text) and depth:
                if text[cursor] == "(":
                    depth += 1
                elif text[cursor] == ")":
                    depth -= 1
                cursor += 1
            inner = text[function.end(): cursor - 1]
            operands.append(
                {
                    "kind": "function",
                    "name": function.group("name"),
                    "operands": _expression_operands(inner),
                }
            )
            index = cursor
            continue
        if char == "(":
            depth, cursor = 1, index + 1
            while cursor < len(text) and depth:
                if text[cursor] == "(":
                    depth += 1
                elif text[cursor] == ")":
                    depth -= 1
                cursor += 1
            operands.append({"kind": "group", "operands": _expression_operands(text[index + 1: cursor - 1])})
            index = cursor
            continue
        reference = re.match(r"(?:pname|ptext|sname|fname):[A-Za-z0-9_]+", text[index:])
        if reference:
            operands.append({"kind": "reference", "value": reference.group(0).split(":", 1)[1]})
            index += len(reference.group(0))
            continue
        token = re.match(r"[A-Za-z_][A-Za-z0-9_]*", text[index:])
        if token:
            operands.append({"kind": "reference", "value": token.group(0)})
            index += len(token.group(0))
            continue
        number = re.match(r"\d+(?:\.\d+)?", text[index:])
        if number:
            value = float(number.group(0)) if "." in number.group(0) else int(number.group(0))
            operands.append({"kind": "number", "value": value})
            index += len(number.group(0))
            continue
        return [{"kind": "unknown-composite", "text": text}]
    return operands


def interpret_limit_value(expression: str) -> dict:
    """Interpret a required-limits value without losing information.

    Handles integers, decimals, powers (2^30^ or 2^22), fractions, arithmetic,
    max()/min() over references, tuples and ranges, ULP-adjusted bounds,
    enumerant expressions and descriptive values. Anything that cannot be
    interpreted is returned as kind "unknown" so the caller fails loudly instead
    of stripping characters.
    """
    raw = expression.strip()
    text = FOOTNOTE_RE.sub(" ", raw).strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[\u00d7\u2715\u2a2f]", "*", text)
    text = text.replace("{plus}", "+").replace("{times}", "*").replace("{minus}", "-")
    equation = re.fullmatch(r"\[eq\]#(.*)#", text, re.S)
    if equation:
        text = equation.group(1).strip()
    ulp_adjusted = False
    if not text.startswith("("):
        match = ULP_SUFFIX_RE.match(text)
        if match:
            ulp_adjusted = True
            text = match.group("head").strip()
    lowered = text.lower()
    if lowered in DESCRIPTIVE_VALUES:
        return {"kind": DESCRIPTIVE_VALUES[lowered], "value": lowered, "ulp_adjusted": ulp_adjusted, "raw": raw}
    if text in ("", "-"):
        return {"kind": "none", "value": None, "ulp_adjusted": ulp_adjusted, "raw": raw}
    if text.startswith("(") and text.endswith(")") and not FUNCTION_RE.match(text):
        elements = [_split_top_level(text[1:-1])]
        values, kinds = [], []
        for element in elements[0]:
            parsed = interpret_limit_value(element)
            kinds.append(parsed["kind"])
            values.append(parsed.get("values") if parsed["kind"] == "tuple" else parsed.get("value"))
        if "unknown" in kinds:
            return {"kind": "unknown", "raw": raw}
        return {"kind": "tuple", "values": values, "element_kinds": kinds, "ulp_adjusted": ulp_adjusted, "raw": raw}
    if text.startswith(ENUM_PREFIXES) or text in ("VK_TRUE", "VK_FALSE"):
        return {"kind": "enum", "value": text, "ulp_adjusted": ulp_adjusted, "raw": raw}
    if re.fullmatch(r"(?:pname|ptext):[A-Za-z0-9_]+", text):
        return {"kind": "reference", "value": REFERENCE_PREFIX_RE.sub("", text), "ulp_adjusted": ulp_adjusted, "raw": raw}
    value = evaluate_arithmetic(text)
    if value is not None:
        kind = "integer" if isinstance(value, int) else "decimal"
        return {"kind": kind, "value": value, "ulp_adjusted": ulp_adjusted, "raw": raw}
    if any(token in text for token in ("+", "*", "/", "max(", "min(")) or re.search(r"pname:|\b[A-Za-z_]", text):
        normalised = POWER_RE.sub(lambda m: str(int(m.group(1)) ** int(m.group(2))), text)
        operands = _expression_operands(normalised)
        if operands and all(operand["kind"] != "unknown-composite" for operand in operands):
            return {"kind": "expression", "operands": operands, "ulp_adjusted": ulp_adjusted, "raw": raw}
    kind, simple = interpret_number(text)
    if kind != "unknown":
        return {"kind": kind, "value": simple, "ulp_adjusted": ulp_adjusted, "raw": raw}
    return {"kind": "unknown", "raw": raw}


def evaluate_operands(operands: list, parsed: dict):
    """Evaluate a token list, resolving references and max()/min() functions."""
    total, pending_operator = None, "+"
    for operand in operands:
        kind = operand["kind"]
        if kind == "operator":
            pending_operator = operand["value"]
            continue
        if kind == "number":
            value = operand["value"]
        elif kind == "reference":
            value = parsed.get(operand["value"], {}).get("required_for_core_1_4")
            if value is None:
                return None
        elif kind in ("function", "group"):
            inner = evaluate_operands(operand["operands"], parsed)
            if isinstance(inner, list):
                inner = max(inner) if operand.get("name") == "max" else (min(inner) if operand.get("name") == "min" else None)
            if inner is None:
                return None
            value = inner
        else:
            return None
        if total is None:
            total = value
        elif pending_operator == "+":
            total = total + value
        elif pending_operator == "-":
            total = total - value
        elif pending_operator == "*":
            total = total * value
        elif pending_operator == "/":
            total = total / value
        else:
            return None
    return total


def combine(values: list, types: list, kinds: list):
    """Combine core-tagged values: max for min-type, min for max-type."""
    if not values:
        return None
    if all(kind in ("none",) for kind in kinds):
        return None
    scalars = [value for value, kind in zip(values, kinds) if kind not in ("none", "enum") and not isinstance(value, list)]
    if len(scalars) == len([kind for kind in kinds if kind not in ("none", "enum")]) and scalars and not any(isinstance(value, list) for value in values):
        kinds_of_types = [t for t in types if t]
        prefer_min = bool(kinds_of_types) and kinds_of_types[0].startswith("min")
        return max(scalars) if prefer_min else min(scalars)
    lists = [value for value in values if isinstance(value, list)]
    if lists:
        length = max(len(item) for item in lists)
        out = []
        for index in range(length):
            column = [item[index] for item in lists if len(item) > index and item[index] is not None]
            if not column:
                out.append(None)
                continue
            element_type = types[index] if index < len(types) else (types[0] if types else "min")
            out.append(max(column) if element_type.startswith("min") else min(column))
        return out
    return None


def resolve_limit_references(parsed: dict) -> dict:
    """Resolve symbolic values; an unknown reference is a hard failure."""
    # Resolve symbolic values ("pname:otherLimit") against the referenced row so
    # the requirement is a real number instead of a name.
    for record in parsed.values():
        references = []
        for entry in record["values"]:
            if entry["kind"] == "reference":
                references.append(entry["value"])
            elif entry["kind"] == "tuple":
                references.extend([value for value, kind in zip(entry["values"], entry["element_kinds"]) if kind == "reference"])
        for reference in references:
            if reference not in parsed:
                raise SystemExit("limit value references unknown limit %r" % reference)
        if record["required_for_core_1_4"] is None:
            numeric = []
            for entry in record["values"]:
                if not (not entry["tags"] or {"core", "1_4"} & set(entry["tags"])):
                    continue
                if entry["kind"] == "reference" and parsed[entry["value"]]["required_for_core_1_4"] is not None:
                    numeric.append(parsed[entry["value"]]["required_for_core_1_4"])
                elif entry["kind"] == "expression":
                    values = []
                    resolvable = True
                    for operand in entry["operands"]:
                        if operand["kind"] == "reference":
                            target = parsed.get(operand["value"], {}).get("required_for_core_1_4")
                            if target is None:
                                resolvable = False
                                break
                            values.append(target)
                        else:
                            values.append(operand["value"])
                    if resolvable and values:
                        total = values[0]
                        for operator, value in zip(entry["operators"], values[1:]):
                            total = total + value if operator == "+" else (total * value if operator == "*" else total - value)
                        numeric.append(total)
                elif entry["kind"] in ("integer", "decimal", "power", "fraction"):
                    numeric.append(entry["value"])
            if numeric:
                prefer_min = record["limit_types"] and record["limit_types"][0].startswith("min")
                record["required_for_core_1_4"] = max(numeric) if prefer_min else min(numeric)
                record["required_kind"] = "decimal" if any(isinstance(value, float) for value in numeric) else "integer"
                record["resolved_from_symbolic_values"] = references
            elif references:
                record["required_kind"] = "reference"
                record["resolved_from_symbolic_values"] = references
    return parsed


def parse_limits_table(adoc: str) -> list[dict]:
    """Parse the Required Limits table, interpreting every value.

    Version tags decide applicability ({core}/{limit1_4} for the core target,
    {limit2022}/{limit2024}/{limit2026} recorded separately). Unknown
    expressions raise instead of being silently mangled.
    """
    PIPES = "\u0000"
    rows: list[list[str]] = []
    previous_continues = False
    for raw in adoc_table_block(adoc, "limits-required").splitlines():
        line = raw.strip()
        if not line:
            continue
        if previous_continues and not line.startswith("|"):
            parts = [cell.strip() for cell in line.replace("\\|", PIPES).split("|")]
            if rows:
                rows[-1][-1] = (rows[-1][-1] + " + " + parts[0]).strip()
                for extra in parts[1:]:
                    if extra:
                        rows[-1].append(extra)
            previous_continues = line.endswith("+")
            continue
        if not line.startswith("|"):
            continue
        cells = [cell.strip().replace(PIPES, "|") for cell in line.replace("\\|", PIPES).split("|")[1:]]
        previous_continues = line.endswith("+")
        if previous_continues and cells:
            cells[-1] = cells[-1][:-1].strip()
        while len(cells) < 3:
            cells.append("")
        rows.append(cells)

    parsed: dict[str, dict] = {}
    for cells in rows:
        if len(cells) < 4 or "pname:" not in cells[0]:
            continue
        name = re.sub(r"^.*pname:", "", cells[0]).strip().split()[0]
        type_like = re.compile(r"^(min|max|min,|max,|recommendation|implementation-dependent|Boolean|fixed point increment|\(max|min\))")
        cells = [cell for cell in cells if cell != ""] or [""]
        if len(cells) >= 3 and type_like.match(cells[-1]):
            supported_cell, type_cell = cells[-2], cells[-1]
        elif len(cells) >= 2:
            supported_cell, type_cell = cells[-1], ""
        else:
            supported_cell, type_cell = "", ""
        cells = [cells[0], supported_cell, type_cell]
        value_records = []
        keep_none = len(re.findall(r"\((?=[^)]*\{)", supported_cell)) == 0
        chunks = [chunk.strip().strip("+").strip() for chunk in re.split(r"\s\+\s|\s\+$", supported_cell)]
        for chunk in [c for c in chunks if c]:
            chunk = FOOTNOTE_RE.sub(" ", chunk).strip()
            match = VALUE_TAGS_RE.fullmatch(chunk)
            if match:
                raw_value = FOOTNOTE_RE.sub(" ", match.group("value")).strip()
                tags = [tag.strip("{}").replace("limit", "") for tag in TAG_RE_SPLIT.split(match.group("tags")) if tag.strip("{}")]
            else:
                raw_value = FOOTNOTE_RE.sub(" ", chunk).strip()
                tags = []
            if not raw_value:
                raw_value = "-" if keep_none else ""
            interpretation = interpret_limit_value(raw_value)
            if interpretation["kind"] == "unknown":
                raise SystemExit("uninterpretable limit value for %s: %r" % (name, raw_value))
            value_records.append({"value": raw_value, "tags": tags, **interpretation})
        if not value_records:
            interpretation = interpret_limit_value(supported_cell)
            if interpretation["kind"] == "unknown":
                raise SystemExit("uninterpretable limit value for %s: %r" % (name, supported_cell))
            value_records.append({"value": supported_cell, "tags": [], **interpretation})
        limit_types = [part.strip() for part in re.split(r",", type_cell.replace("*", "").replace("^", "")) if part.strip()]
        base_type = limit_types[0] if limit_types else "unspecified"
        core_values = [entry for entry in value_records if not entry["tags"] or {"core", "1_4"} & set(entry["tags"])]
        kinds = [entry["kind"] for entry in core_values]
        values = [entry.get("values") if entry["kind"] == "tuple" else entry.get("value") for entry in core_values]
        required = combine(values, limit_types, kinds)
        if required is None and all(kind == "enum" for kind in kinds) and kinds:
            required = core_values[-1].get("value")
        required_kind = "none"
        if kinds:
            if any(kind == "tuple" for kind in kinds):
                required_kind = "tuple"
            elif all(kind in ("integer", "decimal", "power", "fraction") for kind in kinds):
                required_kind = "decimal" if any(kind == "decimal" for kind in kinds) else "integer"
            elif any(kind == "enum" for kind in kinds):
                required_kind = "enum"
        record = {
            "limit": name,
            "limit_type": base_type,
            "limit_types": limit_types,
            "required_kind": required_kind,
            "required_for_core_1_4": required,
            "values": value_records,
            "roadmap_only_values": [entry for entry in value_records if set(entry["tags"]) & {"2022", "2024", "2026"}],
        }
        existing = parsed.get(name)
        if existing is None or len(record["values"]) > len(existing["values"]):
            parsed[name] = record

    resolve_limit_references(parsed)
    return [parsed[name] for name in sorted(parsed)]


FEATURE_BIT_RE = re.compile(r"ename:(VK_FORMAT_FEATURE[A-Z0-9_]*)")
FEATURE_COND_RE = re.compile(r"pname:([A-Za-z0-9_]+)[^.]{0,40}?feature")
EXTENSION_COND_RE = re.compile(r"apiext:(VK_[A-Za-z0-9_]+)")
SCOPE_TABLE_ANCHORS = [
    ("formats-feature-bits-in-optimaltilingfeatures-table", "optimalTilingFeatures"),
    ("formats-feature-bits-in-bufferfeatures-table", "bufferFeatures"),
]


def parse_column_scopes(adoc: str) -> dict:
    """Column -> effective scope, from the specification's feature-bit tables.

    The mandatory format tables use the columns defined for
    optimalTilingFeatures and bufferFeatures, so every cell (including {sym1})
    has an effective scope. Columns guarded by an ifdef keep that guard.
    """
    scopes: dict[str, dict] = {}
    for anchor, scope in SCOPE_TABLE_ANCHORS:
        try:
            block = adoc_table_block(adoc, anchor)
        except SystemExit:
            continue
        guards: list[str] = []
        for line in block.splitlines():
            stripped = line.strip()
            guard = IFDEF_RE.match(stripped)
            if guard:
                guards.append(guard.group(1))
                continue
            if stripped.startswith("endif::"):
                if guards:
                    guards.pop()
                continue
            feature = FEATURE_BIT_RE.match(stripped.lstrip("|").strip())
            if feature:
                scopes[feature.group(1)] = {"scope": scope, "guard": guards[-1] if guards else None}
    return scopes


SYMBOL_RE = re.compile(r"\{sym(\d)\}")
IFDEF_RE = re.compile(r"^ifdef::([^\[]+)\[\]$")
SCOPE_RE = re.compile(r"pname:(linearTilingFeatures|optimalTilingFeatures|bufferFeatures)")


def parse_symbol_legend(adoc: str) -> dict:
    """The global key table: what {sym1}..{sym4} mean outside a specific table."""
    legend = {}
    block = adoc_table_block(adoc, "formats-key-for-format-feature-tables-table")
    current = None
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith("^|{sym"):
            current = SYMBOL_RE.search(stripped).group(0)
            legend[current] = stripped.split("|", 2)[-1].strip()
        elif current and stripped and not stripped.startswith("|"):
            legend[current] = (legend[current] + " " + stripped).strip()
    return {key: re.sub(r"\s+", " ", value) for key, value in legend.items()}


IFDEF_MARKER_RE = re.compile(r"^ifdef::(?P<guard>[A-Za-z0-9_,]+)\[\{sym(?P<symbol>\d)\}\]$")
ANNOTATION_LINE_RE = re.compile(r"^(?P<span>\d+)\+\|\s*(?P<text>.*)$")
COLUMN_HEADER_RE = re.compile(r"^(?P<span>\d+)\+>")
FORMAT_ROW_RE = re.compile(r"^\|\s*ename:(?P<format>VK_FORMAT_[A-Z0-9_]+)\s*\|(?P<rest>.*)$")


FORMAT_ANCHOR_RE = re.compile(r"ename:(VK_FORMAT_[A-Z0-9_]+)")
TABLE_ANCHOR_RE = re.compile(r"<<(formats-mandatory-features-[a-z0-9-]+)")
NEGATIVE_RULE_RE = re.compile(r"must:? not (?:support|advertise)")
FEATURE_IS_SUPPORTED_RE = re.compile(r"pname:([A-Za-z0-9_]+)[^.]{0,40}?feature is supported")
SUPPORTS_FEATURE_RE = re.compile(r"supports the\s+[^.]{0,80}?pname:([A-Za-z0-9_]+)[^.]{0,20}?feature")
ANY_OF_RE = re.compile(r"at least one of", re.I)


def _classify_annotation(text: str, guard: str | None, legend: dict) -> dict:
    """Resolve one table annotation into an explicit rule.

    Kinds: symbol-rule (a {symN} marker), negative-scope-rule (a scope that must
    not advertise features), column-rule (a feature bit with a condition),
    any-of-formats-rule (a feature required for at least one of several formats),
    table-choice-rule (a feature required in one of several format tables) and
    unresolved-rule (kept for the validator to reject).
    """
    flat = re.sub(r"\s+", " ", text).strip()
    symbol_match = SYMBOL_RE.search(flat)
    scope_match = SCOPE_RE.search(flat)
    feature_matches = sorted(set(FEATURE_BIT_RE.findall(flat)))
    extensions = sorted(set(EXTENSION_COND_RE.findall(flat)))
    feature_conditions = sorted(set(FEATURE_IS_SUPPORTED_RE.findall(flat)) | {name for name in SUPPORTS_FEATURE_RE.findall(flat) if name not in ("VkPhysicalDevice",)})
    format_options = sorted(set(FORMAT_ANCHOR_RE.findall(flat)))
    table_options = sorted(set(TABLE_ANCHOR_RE.findall(flat)))

    reasons, kind = [], None
    if NEGATIVE_RULE_RE.search(flat):
        kind = "negative-scope-rule"
        reasons.append("%s must not advertise features for these formats" % (scope_match.group(1) if scope_match else "the named scope"))
    elif ANY_OF_RE.search(flat) and table_options:
        kind = "table-choice-rule"
        reasons.append("required for all formats of one of: %s" % ", ".join(table_options))
    elif ANY_OF_RE.search(flat) and format_options:
        kind = "any-of-formats-rule"
        reasons.append("required for at least one of: %s" % ", ".join(format_options))
    else:
        if extensions:
            reasons.append("requires the %s extension" % ", ".join(extensions))
        if feature_conditions:
            reasons.append("requires the %s feature" % ", ".join(feature_conditions))
        if symbol_match:
            kind = "symbol-rule"
        elif scope_match:
            kind = "scope-rule"
        elif feature_matches:
            kind = "column-rule"
    if kind is None:
        kind = "unresolved-rule"
    if kind in ("column-rule", "any-of-formats-rule", "table-choice-rule") and not reasons:
        kind = "unresolved-rule"
    return {
        "kind": kind,
        "symbol": symbol_match.group(0) if symbol_match else None,
        "features": feature_matches,
        "format_options": format_options,
        "table_options": table_options,
        "scope": scope_match.group(1) if scope_match else None,
        "guard": guard,
        "condition_kind": "resolved" if reasons else "unresolved",
        "condition": " and ".join(reasons) if reasons else flat,
        "legend_condition": legend.get(symbol_match.group(0)) if symbol_match else None,
        "text": flat,
    }


def parse_formats_tables(adoc: str) -> list[dict]:
    """Parse the mandatory format tables into per-cell obligations.

    Every cell keeps its symbol, its effective scope, its resolved conditions and
    any guard - including rows written across several physical lines and markers
    emitted inline by ``ifdef::EXT[{symN}]``. Annotations are kept as a list, so a
    table may carry several rules (symbol-scoped, scope-scoped or column-scoped)
    without any of them overwriting another; an annotation that cannot be
    resolved is recorded as such instead of being dropped.
    """
    legend = parse_symbol_legend(adoc)
    column_scopes = parse_column_scopes(adoc)
    tables = []
    for match in re.finditer(r"\[\[(formats-mandatory-features-[a-z0-9-]+)\]\][\s\S]{0,4000}?\|====([\s\S]*?)\|====", adoc):
        anchor, block = match.group(1), match.group(2)
        title = re.search(r"^\.(.+)$", adoc[match.start(): match.start() + 200], re.M)
        columns = []
        for line in block.splitlines():
            column = re.match(r"\s*(\d+)\+>.*ename:(VK_FORMAT_FEATURE[A-Z0-9_]*)", line)
            if column:
                columns.append((int(column.group(1)), column.group(2)))
        columns.sort()
        column_names = [feature for _, feature in columns]
        expected_cells = len(column_names) + 1  # the leading Format column

        annotations: list[dict] = []
        rows: list[dict] = []
        guards: list[str] = []
        current = None
        pending_annotation = None

        def flush_row():
            nonlocal current
            if current is not None:
                rows.append(current)
                current = None

        def flush_annotation():
            nonlocal pending_annotation
            if pending_annotation is not None:
                annotations.append(_classify_annotation(pending_annotation["text"], pending_annotation["guard"], legend))
                pending_annotation = None

        for raw in block.splitlines():
            stripped = raw.strip()
            marker = IFDEF_MARKER_RE.match(stripped)
            if marker:
                # Guards a single marker inside an open cell: the marker is the
                # cell content and the guard limits it to that extension.
                if current is not None and current["cells"]:
                    current["cells"][-1] = (current["cells"][-1] + "{sym%s}" % marker.group("symbol")).strip()
                    current["cell_guards"][-1] = marker.group("guard")
                continue
            guard = IFDEF_RE.match(stripped)
            if guard:
                guards.append(guard.group(1))
                continue
            if stripped.startswith("endif::"):
                if guards:
                    guards.pop()
                continue
            annotation = ANNOTATION_LINE_RE.match(stripped)
            if annotation:
                flush_row()
                flush_annotation()
                pending_annotation = {"text": annotation.group("text"), "guard": guards[-1] if guards else None}
                continue
            if COLUMN_HEADER_RE.match(stripped):
                continue
            row = FORMAT_ROW_RE.match(stripped)
            if row:
                flush_row()
                flush_annotation()
                current = {
                    "format": row.group("format"),
                    "guard": guards[-1] if guards else None,
                    "cells": [""],
                    "cell_guards": [guards[-1] if guards else None],
                }
                for part in row.group("rest").split("|"):
                    current["cells"].append(part.strip())
                    current["cell_guards"].append(guards[-1] if guards else None)
                continue
            if current is not None and (stripped.startswith("|") or stripped == "" or set(stripped) <= set("| ")):
                parts = stripped.split("|")
                first = parts[0].strip()
                if first:
                    current["cells"][-1] = (current["cells"][-1] + " " + first).strip()
                for part in parts[1:]:
                    current["cells"].append(part.strip())
                    current["cell_guards"].append(guards[-1] if guards else None)
                continue
            if pending_annotation is not None:
                pending_annotation["text"] += " " + stripped
                continue
        flush_row()
        flush_annotation()

        # Normalise the cell count against the column layout, then build one
        # obligation per cell: symbol, effective scope, resolved conditions and
        # guard, attributed to the table rules that actually apply to it.
        column_conditions: dict[str, list[dict]] = {}
        for annotation in annotations:
            if annotation["symbol"] is not None:
                continue
            for feature in annotation["features"]:
                column_conditions.setdefault(feature, []).append(annotation)

        entries = []
        for entry in rows:
            values = list(entry["cells"])
            guards_for_cells = list(entry["cell_guards"])
            while len(values) > expected_cells and not values[-1]:
                values.pop()
                guards_for_cells.pop()
            while len(values) < expected_cells:
                values.append("")
                guards_for_cells.append(entry["guard"])
            cells = []
            for index, feature in enumerate(column_names):
                value = values[index + 1] if index + 1 < len(values) else ""
                if not value:
                    continue
                symbol_match = SYMBOL_RE.fullmatch(value)
                if not symbol_match:
                    raise SystemExit("unknown format table marker %r for %s" % (value, entry["format"]))
                symbol = symbol_match.group(0)
                applicable = [
                    rule
                    for rule in annotations
                    if (rule["symbol"] and rule["symbol"] == symbol) or (feature in rule["features"])
                ]
                rule_scopes = sorted({rule["scope"] for rule in applicable if rule["scope"]})
                column_scope = column_scopes.get(feature, {})
                effective_scope = rule_scopes[0] if rule_scopes else column_scope.get("scope")
                conditions = [rule["condition"] for rule in applicable if rule["condition"]]
                guard = guards_for_cells[index + 1] or entry["guard"] or column_scope.get("guard")
                if column_scope.get("guard") and not rule_scopes:
                    column_note = "column guarded by %s" % column_scope["guard"]
                    if column_note not in conditions:
                        conditions.append(column_note)
                for rule in applicable:
                    marker = "guarded by %s" % rule["guard"]
                    if rule["guard"] and marker not in conditions:
                        conditions.append(marker)
                cells.append(
                    {
                        "feature": feature,
                        "symbol": symbol,
                        "required": symbol == "{sym1}" and not conditions,
                        "scope": effective_scope,
                        "rule_scopes": rule_scopes,
                        "scope_kind": "rule" if rule_scopes else ("column" if column_scope.get("scope") else "table-defined"),
                        "conditions": conditions,
                        "guard": guard,
                        "applicable_rules": len(applicable),
                    }
                )
            required = [cell["feature"] for cell in cells if cell["required"] and not cell["conditions"]]
            conditional = [cell for cell in cells if not (cell["required"] and not cell["conditions"])]
            entries.append(
                {
                    "format": entry["format"],
                    "guard": entry["guard"],
                    "cells": cells,
                    "required_feature_bits": required,
                    "conditional_feature_bits": conditional,
                }
            )
        if entries:
            tables.append(
                {
                    "anchor": anchor,
                    "title": title.group(1).strip() if title else anchor,
                    "columns": column_names,
                    "symbol_legend": legend,
                    "annotations": annotations,
                    "column_conditions": {feature: [rule["condition"] for rule in rules] for feature, rules in column_conditions.items()},
                    "column_scopes": {feature: entry for feature, entry in column_scopes.items() if feature in column_names},
                    "rows": entries,
                }
            )
    return tables


COMMAND_AREAS = [
    ("instance-device", ("vkCreateInstance", "vkDestroyInstance", "vkEnumerateInstance", "vkEnumeratePhysicalDevice", "vkGetPhysicalDevice", "vkCreateDevice", "vkDestroyDevice", "vkGetDevice")),
    ("memory", ("vkAllocateMemory", "vkFreeMemory", "vkMapMemory", "vkUnmapMemory", "vkFlushMappedMemory", "vkInvalidateMappedMemory")),
    ("buffers", ("vkCreateBuffer", "vkDestroyBuffer", "vkBindBufferMemory", "vkGetBufferMemoryRequirements", "vkCreateBufferView")),
    ("images", ("vkCreateImage", "vkDestroyImage", "vkBindImageMemory", "vkGetImageMemoryRequirements", "vkCreateImageView", "vkGetImageSubresource")),
    ("samplers", ("vkCreateSampler", "vkDestroySampler")),
    ("descriptors", ("vkCreateDescriptor", "vkDestroyDescriptor", "vkResetDescriptor", "vkAllocateDescriptor", "vkFreeDescriptor", "vkUpdateDescriptor", "vkCreatePipelineLayout", "vkDestroyPipelineLayout")),
    ("pipelines-and-shaders", ("vkCreateShaderModule", "vkDestroyShaderModule", "vkCreatePipelineCache", "vkDestroyPipelineCache", "vkCreateComputePipelines", "vkCreateGraphicsPipelines", "vkDestroyPipeline")),
    ("command-buffers", ("vkCreateCommandPool", "vkDestroyCommandPool", "vkResetCommandPool", "vkAllocateCommandBuffers", "vkFreeCommandBuffers", "vkBeginCommandBuffer", "vkEndCommandBuffer", "vkResetCommandBuffer")),
    ("synchronization", ("vkCreateFence", "vkDestroyFence", "vkResetFences", "vkGetFenceStatus", "vkWaitForFences", "vkCreateSemaphore", "vkDestroySemaphore", "vkCreateEvent", "vkDestroyEvent", "vkSetEvent", "vkResetEvent", "vkQueueSubmit", "vkQueueWaitIdle", "vkDeviceWaitIdle")),
    ("queries", ("vkCreateQueryPool", "vkDestroyQueryPool", "vkGetQueryPoolResults")),
]


EXT_RULE_RE = re.compile(r"^(?P<exts>.+?)\s*,?\s*if the (?P<feature>[A-Za-z0-9_]+) feature is supported\.?$")


def parse_extension_rule(text: str) -> dict:
    """Give the residual rules a taxonomy instead of leaving them as prose.

    Two shapes occur in the pinned section: "extension X (or core version), if
    feature Y is supported" (an extension requirement triggered by a feature),
    and the 1.4 queue-family / host-image-copy either-or rule.
    """
    match = EXT_RULE_RE.match(text.strip())
    if match:
        raw = match.group("exts").replace(" extension", "").replace("the ", "")
        extensions = [name.strip() for name in re.split(r",|\bor\b", raw) if name.strip()]
        return {
            "kind": "extension-required-by-feature",
            "extensions": extensions,
            "trigger": {"kind": "feature", "name": match.group("feature")},
            "requirement": {"kind": "any-of", "extensions": extensions},
            "text": text.strip(),
            "explanation": "One of these extensions (or the named core version) must be supported when %s is supported" % match.group("feature"),
        }
    if "hostImageCopy" in text:
        return {
            "kind": "either-or",
            "options": ["hostImageCopy feature supported", "an additional transfer-capable queue family reported"],
            "requirement": {"kind": "any-of", "features": ["hostImageCopy"]},
            "trigger": {"kind": "graphics-queue-without-extra-transfer-queue"},
            "text": text.strip(),
            "explanation": "A graphics-only queue configuration must provide either host image copy or an extra transfer-capable queue family",
        }
    return {"kind": "unclassified", "text": text.strip(), "explanation": ""}


def classify_commands(commands: list[str]) -> dict:
    """Group the resolved core command surface into differentiable contracts."""
    contracts: dict[str, list[str]] = {name: [] for name, _ in COMMAND_AREAS}
    contracts["command-recording"] = []
    contracts["other"] = []
    for command in commands:
        if command.startswith("vkCmd"):
            contracts["command-recording"].append(command)
            continue
        for name, prefixes in COMMAND_AREAS:
            if any(command.startswith(prefix) for prefix in prefixes):
                contracts[name].append(command)
                break
        else:
            contracts["other"].append(command)
    return {name: value for name, value in contracts.items() if value}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sources", default=DEFAULT_SOURCES)
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--spec-html", help="local copy of the pinned specification HTML")
    parser.add_argument("--vk-xml", help="local copy of the pinned registry vk.xml")
    parser.add_argument("--limits-adoc", help="local copy of the pinned chapters/limits.adoc")
    parser.add_argument("--formats-adoc", help="local copy of the pinned chapters/formats.adoc")
    args = parser.parse_args(argv)

    sources = load_sources(args.sources)
    spec = find_source(sources, SPEC_SOURCE_ID)
    registry = find_source(sources, REGISTRY_SOURCE_ID)
    alias = spec["document_alias"]
    vk_xml_artifact = next(a for a in registry["artifacts"] if a["path"] == "registry/vk.xml")
    limits_artifact = next(a for a in spec["artifacts"] if a["path"] == "chapters/limits.adoc")
    formats_artifact = next(a for a in spec["artifacts"] if a["path"] == "chapters/formats.adoc")

    html = read_input(args.spec_html, alias["url"], alias["sha256"], "specification").decode("utf-8", "replace")
    title = re.search(r"<title>([^<]*)</title>", html, re.IGNORECASE)
    if not title or spec["spec_version"] not in title.group(1):
        raise SystemExit("specification title does not report %s" % spec["spec_version"])
    xml_bytes = read_input(
        args.vk_xml,
        "https://raw.githubusercontent.com/KhronosGroup/Vulkan-Headers/%s/%s" % (registry["commit"], vk_xml_artifact["path"]),
        vk_xml_artifact["sha256"],
        "registry",
    )

    features = parse_feature_requirements(html)
    surface = parse_vk_xml(xml_bytes.decode("utf-8"))
    limits_bytes = read_input(
        args.limits_adoc,
        "https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/%s/%s" % (spec["commit"], limits_artifact["path"]),
        limits_artifact["sha256"],
        "limits chapter",
    )
    formats_bytes = read_input(
        args.formats_adoc,
        "https://raw.githubusercontent.com/KhronosGroup/Vulkan-Docs/%s/%s" % (spec["commit"], formats_artifact["path"]),
        formats_artifact["sha256"],
        "formats chapter",
    )
    limits_table = parse_limits_table(limits_bytes.decode("utf-8"))
    formats_tables = parse_formats_tables(formats_bytes.decode("utf-8"))
    resolved_commands = surface["surface_by_profile"]["graphics_resolved"]["commands"]
    contracts = classify_commands(resolved_commands)

    spec_by_version = {}
    unconditional: list[dict] = []
    conditional: list[dict] = []
    at_least_one: list[dict] = list(features["at_least_one"])
    for version, entries in sorted(features["by_version"].items()):
        bits, conditional_bits = [], []
        for entry in entries:
            record = {
                "features": entry["features"],
                "condition": entry["condition"],
                "at_least_one": entry["at_least_one"],
                "text": entry["text"],
            }
            if entry["at_least_one"]:
                at_least_one.append(dict(record, version=version))
            elif entry["condition"] and "is not advertised" in entry["condition"]:
                # A negative condition ("unless this extension is advertised")
                # holds for any implementation that does not advertise the
                # named extension, so the obligation is treated as
                # unconditional and the condition is preserved as a note.
                record["note"] = "condition: " + entry["condition"]
                bits.append(record)
                unconditional.append(dict(record, version=version))
            elif entry["condition"]:
                conditional_bits.append(record)
                conditional.append(dict(record, version=version))
            else:
                bits.append(record)
                unconditional.append(dict(record, version=version))
        spec_by_version[version] = {"unconditional": bits, "conditional": conditional_bits}
    conditional_on_optional_extension = []
    any_of_groups = 0
    for entry in features["conditional_features"] + features.get("by_version", {}).get("__none__", []):
        if not isinstance(entry, dict) or "features" not in entry:
            continue
        trigger = entry.get("trigger") or parse_trigger(" or ".join(entry.get("extensions", [])) + " is supported")
        record = {
            "features": list(entry["features"]),
            "requirement": entry.get("requirement") or (
                {"kind": "any-of", "features": list(entry["features"])}
                if entry.get("at_least_one") and len(entry["features"]) > 1
                else {"kind": "feature", "features": list(entry["features"][:1])}
            ),
            "trigger": trigger,
            "condition": entry.get("condition") or condition_explanation(trigger),
            "at_least_one": bool(entry.get("at_least_one")),
            "text": entry["text"],
            "explanation": entry.get("explanation") or "",
            "version": None,
        }
        if record["at_least_one"]:
            any_of_groups += 1
        conditional_on_optional_extension.append(record)
    # Any-of alternatives must not be re-expanded into separate obligations.
    expanded = [entry for entry in conditional_on_optional_extension if len(entry["features"]) == 1 and entry["at_least_one"]]
    if expanded:
        raise SystemExit("any-of group was expanded into single-feature obligations: %r" % expanded[:2])

    # Cross-check the two primary sources: the specification's per-version
    # unconditional feature lists must agree with the registry's per-version
    # <feature> requirement lists.
    spec_bits_by_version = {
        version: sorted({bit for entry in payload["unconditional"] for bit in entry["features"]})
        for version, payload in spec_by_version.items()
    }
    xml_bits_by_version = surface["mandatory_feature_bits_by_version"]
    mismatches = []
    for version in sorted(set(spec_bits_by_version) | set(xml_bits_by_version)):
        spec_bits = set(spec_bits_by_version.get(version, []))
        xml_bits = set(xml_bits_by_version.get(version, []))
        if spec_bits != xml_bits:
            mismatches.append(
                {
                    "version": version,
                    "spec_only": sorted(spec_bits - xml_bits),
                    "registry_only": sorted(xml_bits - spec_bits),
                }
            )
    cumulative_bits = sorted({bit for value in xml_bits_by_version.values() for bit in value})

    output = {
        "schema_version": "1.0",
        "target": {
            "id": "ps5vk-vulkan14-graphics-core",
            "statement": "Declared project target: Vulkan 1.4 core for a graphics implementation. This is a target, not a claim of support.",
            "definition": "The cumulative core obligations of Vulkan 1.0 through 1.4; not a roadmap profile and not a consumer requirement set.",
            "basis": {
                "feature_requirements": {
                    "source_id": SPEC_SOURCE_ID,
                    "anchor": "features-requirements",
                    "spec_version": spec["spec_version"],
                    "document_sha256": alias["sha256"],
                    "note": "Section 'Feature Requirements': every Vulkan graphics implementation must support the listed features per core version, with the stated conditions.",
                },
                "api_surface": {
                    "source_id": REGISTRY_SOURCE_ID,
                    "path": vk_xml_artifact["path"],
                    "sha256": vk_xml_artifact["sha256"],
                    "note": "Per-version <feature> blocks list the commands, types and enums each core version requires.",
                },
                "enforcement_reference": {
                    "source_id": "khronos-vk-gl-cts",
                    "path": "external/vulkancts/modules/vulkan/api/vktApiFeatureInfo.cpp",
                    "note": "The CTS device_mandatory_features case is generated from vkMandatoryFeatures.inl and points at the specification anchor features-requirements.",
                },
            },
        },
        "mandatory_feature_bits": {
            "registry_by_version": xml_bits_by_version,
            "cumulative": cumulative_bits,
            "specification_by_version": spec_by_version,
            "specification_registry_mismatches": mismatches,
            "conditional_in_version_blocks": [
                dict(entry) for entry in conditional if entry["version"] is not None
            ],
            "conditional_on_optional_extension": conditional_on_optional_extension,
            "at_least_one_groups": at_least_one,
            "extension_rules": [parse_extension_rule(text) for text in features["unclassified"]],
        },
        "api_surface": surface,
        "limits": {
            "source_anchor": "limits-required",
            "resolution_rule": "values tagged {core} or {limit1_4} apply to the core target; {limit2022}/{limit2024}/{limit2026} values are roadmap-only and are recorded separately",
            "raised_in_1_4": sorted({row["limit"] for row in limits_table if any("1_4" in value["tags"] for value in row["values"])}),
            "rows": limits_table,
        },
        "formats": {
            "source_anchors": [table["anchor"] for table in formats_tables],
            "resolution_rule": "each row is a format plus the feature bits the specification requires for it; an empty marker means the feature is not mandatory for that format",
            "tables": formats_tables,
        },
        "command_contracts": {
            "resolution_rule": "the resolved core command surface grouped into differentiable contracts by API area; one requirement row per contract",
            "contracts": contracts,
        },
        "roadmap_comparison": {
            "file": "roadmap_comparison.json",
            "note": "Khronos roadmap profiles are recorded separately as a comparison. They are not the definition of core conformance and must not drive classification.",
        },
    }

    tmp = args.out + ".tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2, sort_keys=True)
        handle.write("\n")
    os.replace(tmp, args.out)
    log(
        "wrote %s: %d unconditional bits, %d conditional entries, %d at-least-one groups, %d cumulative commands"
        % (
            args.out,
            len(cumulative_bits),
            len(conditional),
            len(at_least_one),
            len(surface["surface_by_profile"]["graphics_including_base"]["commands"]),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
