#!/usr/bin/env python3
"""Derive the cumulative Vulkan core requirement set for the declared target.

The declared target is **Vulkan 1.4 core for a graphics implementation**. Its
requirement set comes from two pinned primary sources, not from a roadmap
profile:

1. The pinned specification, section "Feature Requirements"
   (anchor ``features-requirements``), which states that all Vulkan graphics
   implementations must support specific features per core version, including
   the conditional ones ("X must be supported if Y is supported") and the
   "at least one of" alternatives. This is the normative source for feature
   bits, and it is what the CTS ``dEQP-VK.info.device_mandatory_features`` case
   is built to enforce.
2. The pinned registry ``vk.xml``, whose per-version ``<feature>`` blocks list
   the commands, types and enums each core version requires. This is the
   normative source for the API surface.

The roadmap profiles are deliberately *not* consulted here; they are a separate
comparison, generated by ``derive_roadmap_comparison.py``.

Both inputs are hash-verified against ``sources.json`` before parsing, so a
moving specification page or a stale registry checkout is a hard failure.

Usage
-----
    python3 conformance_inventory/tools/derive_core_target.py
    python3 conformance_inventory/tools/derive_core_target.py \
        --spec-html /path/to/vkspec.html --vk-xml /path/to/vk.xml
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
INVENTORY_DIR = os.path.dirname(HERE)
DEFAULT_SOURCES = os.path.join(INVENTORY_DIR, "sources.json")
DEFAULT_OUT = os.path.join(INVENTORY_DIR, "core_target.json")

SPEC_SOURCE_ID = "khronos-vulkan-spec"
REGISTRY_SOURCE_ID = "khronos-vulkan-registry"
SECTION_START = 'id="features-requirements"'
TAG_RE = re.compile(r"<(/?)ul>|<(/?)li>")
ANCHOR_FEATURE_RE = re.compile(r'href="#features-([A-Za-z0-9_]+)"')
ANCHOR_EXT_RE = re.compile(r'href="#(VK_[A-Za-z0-9_]+)"')
STRIP_RE = re.compile(r"<[^>]+>")
VERSION_RE = re.compile(r"If Vulkan (1\.[0-9]) is supported")


def log(message: str) -> None:
    print(message, file=sys.stderr)


def load_sources(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def find_source(sources: dict, source_id: str) -> dict:
    for source in sources.get("sources", []):
        if source.get("id") == source_id:
            return source
    raise SystemExit("sources.json has no %s entry" % source_id)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "ps5vk-cis-core-target"})
    with urllib.request.urlopen(request, timeout=180) as response:
        return response.read()


def read_input(local: str | None, url: str, expected_sha256: str, label: str) -> bytes:
    if local:
        with open(local, "rb") as handle:
            data = handle.read()
        origin = local
    else:
        data = fetch(url)
        origin = url
    digest = hashlib.sha256(data).hexdigest()
    if digest != expected_sha256:
        raise SystemExit(
            "stale/incompatible %s pin: %s has sha256 %s, sources.json records %s" % (label, origin, digest, expected_sha256)
        )
    return data


def clean(html_fragment: str) -> str:
    text = STRIP_RE.sub(" ", html_fragment)
    text = text.replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&").replace("&#8217;", "'")
    return re.sub(r"\s+", " ", text).strip()


def list_items(fragment: str, depth: int) -> list[str]:
    """Return the <li> fragments that sit directly inside the list at `depth`."""
    items: list[str] = []
    current = 0
    start = None
    for match in TAG_RE.finditer(fragment):
        tag = match.group(0)
        if tag == "<ul>":
            current += 1
        elif tag == "</ul>":
            current -= 1
        elif tag == "<li>":
            if current == depth:
                start = match.end()
        elif tag == "</li>":
            if current == depth and start is not None:
                items.append(fragment[start:match.start()])
                start = None
    return items


def parse_entry(fragment: str) -> list[dict]:
    text = clean(fragment)
    features = ANCHOR_FEATURE_RE.findall(fragment)
    if not features:
        return []
    at_least_one = "at least one" in text.lower()
    condition = None
    selected = features
    if not at_least_one and " if " in text:
        head, _, tail = text.partition(" if ")
        condition = tail.strip()
        head_features = [name for name in features if name in head]
        selected = head_features or [features[0]]
    elif not at_least_one:
        selected = [features[0]]
    return [{"features": selected, "condition": condition, "at_least_one": at_least_one, "text": text}]


def parse_feature_requirements(html: str) -> dict:
    start = html.find(SECTION_START)
    if start < 0:
        raise SystemExit("pinned specification has no %s anchor" % SECTION_START)
    candidates = [position for position in (html.find("<h3 id=", start + 10), html.find("<h2 id=", start + 10)) if position >= 0]
    end = min(candidates) if candidates else -1
    if end < 0:
        raise SystemExit("could not find the end of the feature-requirements section")
    section = html[start:end]
    if len(section) < 2000:
        raise SystemExit("feature-requirements section looks truncated (%d bytes)" % len(section))

    by_version: dict[str, list[dict]] = {}
    conditional_features: list[dict] = []
    at_least_one: list[dict] = []
    unclassified: list[str] = []
    for item in list_items(section, 1):
        text = clean(item)
        version_match = VERSION_RE.search(text)
        if version_match and "<ul>" in item:
            version = version_match.group(1)
            entries = []
            for nested in list_items(item, 1):
                entries.extend(parse_entry(nested))
            by_version[version] = entries
            continue
        if text.lower().startswith("if ") and ANCHOR_EXT_RE.search(item):
            features = ANCHOR_FEATURE_RE.findall(item)
            extensions = [name for name in ANCHOR_EXT_RE.findall(item) if name not in features]
            conditional_features.append({"extensions": sorted(set(extensions)), "features": features, "text": text})
            continue
        entries = parse_entry(item)
        if entries:
            if entries[0]["at_least_one"]:
                at_least_one.extend(entries)
            else:
                unclassified.extend(entry["text"] for entry in entries)
    return {
        "by_version": by_version,
        "conditional_features": conditional_features,
        "at_least_one": at_least_one,
        "unclassified": unclassified,
        "section_bytes": len(section),
    }


def parse_vk_xml(xml_text: str) -> dict:
    import xml.etree.ElementTree as ET

    root = ET.fromstring(xml_text)
    version_features: dict[str, list[str]] = {}
    profile_surface: dict[str, dict[str, dict[str, list[str]]]] = {}
    for feature in root.findall("feature"):
        name = feature.get("name") or ""
        version_match = re.match(r"VK_VERSION_(1_[0-9])$", name)
        profile_match = re.match(r"VK_(BASE|COMPUTE|GRAPHICS)_VERSION_(1_[0-9])$", name)
        if not version_match and not profile_match:
            continue
        parts = (version_match or profile_match).group(0).split("_")[-2:]
        version = "%s.%s" % (parts[0], parts[1])
        bucket = {"commands": set(), "types": set(), "enums": set(), "features": set()}
        for require in feature.findall("require"):
            for child in require:
                entry_name = child.get("name")
                if not entry_name:
                    continue
                if child.tag == "command":
                    bucket["commands"].add(entry_name)
                elif child.tag == "type":
                    bucket["types"].add(entry_name)
                elif child.tag == "enum":
                    bucket["enums"].add(entry_name)
                elif child.tag == "feature":
                    bucket["features"].add(entry_name)
        if version_match:
            version_features[version] = sorted(bucket["features"])
        else:
            profile = profile_match.group(1).lower()
            profile_surface.setdefault(profile, {})[version] = {
                "commands": sorted(bucket["commands"]),
                "types": sorted(bucket["types"]),
                "enums": sorted(bucket["enums"]),
            }

    versions = {value for surface in profile_surface.values() for value in surface} | set(version_features)
    versions = sorted(versions, key=lambda value: tuple(int(part) for part in value.split(".")))

    def cumulative(profile: str) -> dict:
        acc = {"commands": set(), "types": set(), "enums": set()}
        by_version = {}
        for version in versions:
            entry = profile_surface.get(profile, {}).get(version)
            if entry:
                for key in acc:
                    acc[key].update(entry[key])
            by_version[version] = {
                "commands": entry["commands"] if entry else [],
                "types": entry["types"] if entry else [],
                "enums_count": len(entry["enums"]) if entry else 0,
                "enums_sha1": hashlib.sha1("\n".join(entry["enums"]).encode("utf-8")).hexdigest() if entry else None,
                "cumulative_commands_count": len(acc["commands"]),
                "cumulative_types_count": len(acc["types"]),
            }
        return {
            "by_version": by_version,
            "cumulative": {
                "commands": sorted(acc["commands"]),
                "types": sorted(acc["types"]),
                "enums_count": len(acc["enums"]),
                "enums_sha1": hashlib.sha1("\n".join(sorted(acc["enums"])).encode("utf-8")).hexdigest(),
            },
        }

    graphics = cumulative("graphics")
    base = cumulative("base")
    compute = cumulative("compute")
    combined_commands = sorted(set(graphics["cumulative"]["commands"]) | set(base["cumulative"]["commands"]))
    combined_types = sorted(set(graphics["cumulative"]["types"]) | set(base["cumulative"]["types"]))
    return {
        "versions": versions,
        "mandatory_feature_bits_by_version": version_features,
        "surface_by_profile": {
            "graphics": graphics,
            "base": base,
            "compute": compute,
            "graphics_including_base": {
                "commands_total": len(combined_commands),
                "types_total": len(combined_types),
                "commands": combined_commands,
                "types": combined_types,
            },
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--sources", default=DEFAULT_SOURCES)
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--spec-html", help="local copy of the pinned specification HTML")
    parser.add_argument("--vk-xml", help="local copy of the pinned registry vk.xml")
    args = parser.parse_args(argv)

    sources = load_sources(args.sources)
    spec = find_source(sources, SPEC_SOURCE_ID)
    registry = find_source(sources, REGISTRY_SOURCE_ID)
    alias = spec["document_alias"]
    vk_xml_artifact = next(a for a in registry["artifacts"] if a["path"] == "registry/vk.xml")

    html = read_input(args.spec_html, alias["url"], alias["sha256"], "specification").decode("utf-8", "replace")
    title = re.search(r"<title>([^<]*)</title>", html, re.IGNORECASE)
    if not title or spec["spec_version"] not in title.group(1):
        raise SystemExit("specification title does not report %s" % spec["spec_version"])
    xml_bytes = read_input(
        args.vk_xml,
        "https://raw.githubusercontent.com/KhronosGroup/Vulkan-Headers/%s/%s" % (registry["commit"], vk_xml_artifact["path"]),
        vk_xml_artifact["sha256"],
        "registry",
    )

    features = parse_feature_requirements(html)
    surface = parse_vk_xml(xml_bytes.decode("utf-8"))

    spec_by_version = {}
    unconditional: list[dict] = []
    conditional: list[dict] = []
    at_least_one: list[dict] = list(features["at_least_one"])
    for version, entries in sorted(features["by_version"].items()):
        bits, conditional_bits = [], []
        for entry in entries:
            record = {
                "features": entry["features"],
                "condition": entry["condition"],
                "at_least_one": entry["at_least_one"],
                "text": entry["text"],
            }
            if entry["at_least_one"]:
                at_least_one.append(dict(record, version=version))
            elif entry["condition"] and "is not advertised" in entry["condition"]:
                # A negative condition ("unless this extension is advertised")
                # holds for any implementation that does not advertise the
                # named extension, so the obligation is treated as
                # unconditional and the condition is preserved as a note.
                record["note"] = "condition: " + entry["condition"]
                bits.append(record)
                unconditional.append(dict(record, version=version))
            elif entry["condition"]:
                conditional_bits.append(record)
                conditional.append(dict(record, version=version))
            else:
                bits.append(record)
                unconditional.append(dict(record, version=version))
        spec_by_version[version] = {"unconditional": bits, "conditional": conditional_bits}
    conditional_on_optional_extension = []
    for entry in features["conditional_features"]:
        for feature in entry["features"]:
            conditional_on_optional_extension.append(
                {
                    "features": [feature],
                    "condition": " or ".join(entry["extensions"]) + " is supported",
                    "at_least_one": False,
                    "text": entry["text"],
                    "version": None,
                }
            )

    # Cross-check the two primary sources: the specification's per-version
    # unconditional feature lists must agree with the registry's per-version
    # <feature> requirement lists.
    spec_bits_by_version = {
        version: sorted({bit for entry in payload["unconditional"] for bit in entry["features"]})
        for version, payload in spec_by_version.items()
    }
    xml_bits_by_version = surface["mandatory_feature_bits_by_version"]
    mismatches = []
    for version in sorted(set(spec_bits_by_version) | set(xml_bits_by_version)):
        spec_bits = set(spec_bits_by_version.get(version, []))
        xml_bits = set(xml_bits_by_version.get(version, []))
        if spec_bits != xml_bits:
            mismatches.append(
                {
                    "version": version,
                    "spec_only": sorted(spec_bits - xml_bits),
                    "registry_only": sorted(xml_bits - spec_bits),
                }
            )
    cumulative_bits = sorted({bit for value in xml_bits_by_version.values() for bit in value})

    output = {
        "schema_version": "1.0",
        "target": {
            "id": "ps5vk-vulkan14-graphics-core",
            "statement": "Declared project target: Vulkan 1.4 core for a graphics implementation. This is a target, not a claim of support.",
            "definition": "The cumulative core obligations of Vulkan 1.0 through 1.4; not a roadmap profile and not a consumer requirement set.",
            "basis": {
                "feature_requirements": {
                    "source_id": SPEC_SOURCE_ID,
                    "anchor": "features-requirements",
                    "spec_version": spec["spec_version"],
                    "document_sha256": alias["sha256"],
                    "note": "Section 'Feature Requirements': every Vulkan graphics implementation must support the listed features per core version, with the stated conditions.",
                },
                "api_surface": {
                    "source_id": REGISTRY_SOURCE_ID,
                    "path": vk_xml_artifact["path"],
                    "sha256": vk_xml_artifact["sha256"],
                    "note": "Per-version <feature> blocks list the commands, types and enums each core version requires.",
                },
                "enforcement_reference": {
                    "source_id": "khronos-vk-gl-cts",
                    "path": "external/vulkancts/modules/vulkan/api/vktApiFeatureInfo.cpp",
                    "note": "The CTS device_mandatory_features case is generated from vkMandatoryFeatures.inl and points at the specification anchor features-requirements.",
                },
            },
        },
        "mandatory_feature_bits": {
            "registry_by_version": xml_bits_by_version,
            "cumulative": cumulative_bits,
            "specification_by_version": spec_by_version,
            "specification_registry_mismatches": mismatches,
            "conditional_in_version_blocks": [
                dict(entry) for entry in conditional if entry["version"] is not None
            ],
            "conditional_on_optional_extension": conditional_on_optional_extension,
            "at_least_one_groups": at_least_one,
            "extension_rules_not_core_classification": features["unclassified"],
        },
        "api_surface": surface,
        "roadmap_comparison": {
            "file": "roadmap_comparison.json",
            "note": "Khronos roadmap profiles are recorded separately as a comparison. They are not the definition of core conformance and must not drive classification.",
        },
    }

    tmp = args.out + ".tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        json.dump(output, handle, indent=2, sort_keys=True)
        handle.write("\n")
    os.replace(tmp, args.out)
    log(
        "wrote %s: %d unconditional bits, %d conditional entries, %d at-least-one groups, %d cumulative commands"
        % (
            args.out,
            len(cumulative_bits),
            len(conditional),
            len(at_least_one),
            len(surface["surface_by_profile"]["graphics_including_base"]["commands"]),
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
