#include "resolve_program.h"
#include "runtime_graphics_compiler.h"
#include "spirv_graphics_interface.h"
#include "sample_rate_contract.h"
#include "vk_descriptor.h"
#include <string.h>

/* Generated by tools/build_resolve_shaders.py into the SDK build tree: one
 * averaging fragment per served count plus the vertex stage they pair with. */
#include "resolve_spirv.h"

VkResult ps5vk_resolve_program_acquire(VkDevice device, VkSampleCountFlagBits samples,
    struct ps5vk_resolve_program *out)
{
    (void)device; /* The compile is device-independent: the pair is a program,
                   * and the pass that uses it is what carries the device. */
    if (!out) return VK_ERROR_UNKNOWN;
    out->pair = NULL;
    const uint32_t count = ps5vk_sample_count_number(samples);
    /* Only the counts this profile serves, and only with a stage generated for
     * that count: a resolve of a count nobody generated a stage for would have
     * to read a sample the stage does not name. */
    const uint32_t *fragment = count == 2u ? ps5vk_resolve_fragment_2 :
        count == 4u ? ps5vk_resolve_fragment_4 : NULL;
    if (!fragment) return VK_ERROR_FEATURE_NOT_PRESENT;
    const size_t fragment_words = count == 2u ?
        sizeof(ps5vk_resolve_fragment_2) / 4u : sizeof(ps5vk_resolve_fragment_4) / 4u;
    /* The descriptor contract of the averaging stage: one input attachment,
     * fragment-visible, at set 0 binding 0. */
    struct ps5vk_set_signature set;
    memset(&set, 0, sizeof(set));
    set.count = 1;
    set.binding[0] = (struct ps5vk_binding){.count = 1, .first = 0,
        .stages = VK_SHADER_STAGE_FRAGMENT_BIT};
    set.type[0] = VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT;
    for (unsigned b = 1; b < PS5VK_MAX_BINDINGS; ++b) set.binding[b].first = 1;
    struct ps5vk_graphics_key key = {
        .vertex = {.words = ps5vk_resolve_vertex,
                   .word_count = sizeof(ps5vk_resolve_vertex) / 4u, .entry = "main"},
        .fragment = {.words = fragment, .word_count = fragment_words, .entry = "main"},
        .descriptor_set_count = 1, .descriptor_sets = &set,
        .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
        .color_format = {VK_FORMAT_R8G8B8A8_UNORM}, .color_attachment_count = 1,
        /* The resolve RENDERS INTO a single-sample target, so its own
         * rasterization is single-sample whatever the attachment it reads
         * carries: the front end refuses a pipeline whose sample count does not
         * match the subpass it renders in. */
        .samples = VK_SAMPLE_COUNT_1_BIT, .color_write_mask = {0xfu},
    };
    if (!ps5vk_spirv_graphics_interface(&key)) return VK_ERROR_FEATURE_NOT_PRESENT;
    if (!ps5vk_runtime_graphics_supported(&key)) return VK_ERROR_FEATURE_NOT_PRESENT;
    return ps5vk_runtime_graphics_compile(NULL, &key, &out->pair);
}

void ps5vk_resolve_program_release(VkDevice device, struct ps5vk_resolve_program *program)
{
    (void)device;
    if (!program || !program->pair) return;
    ps5vk_runtime_graphics_free(NULL, program->pair);
    program->pair = NULL;
}
