#!/usr/bin/env python3
"""Embed the pinned upstream reference images the packaged CTS compares against.

The pinned geometry module loads its reference image through
``tcu::ImageIO::loadPNG`` from the data archive. This integration does not carry a
PNG decoder, so the build decodes the pinned assets once and emits them as plain
RGBA8 data; ``cts/upstream/image_io_ps5.cpp`` serves the bytes back through the
same function the module calls. The comparison therefore runs against the
verbatim upstream pixels - a build-time format change, not a different oracle.

Only what the pinned assets actually are is handled: 8-bit RGBA, non-interlaced
PNGs (all 73 geometry reference images are exactly that). Anything else is a hard
error so a changed asset cannot be silently mis-decoded.
"""
from __future__ import annotations

import argparse
import pathlib
import struct
import zlib

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _paeth(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    return b if pb <= pc else c


def decode_rgba8(path: pathlib.Path) -> tuple[int, int, bytes]:
    data = path.read_bytes()
    if not data.startswith(PNG_SIGNATURE):
        raise SystemExit(f"{path}: not a PNG")
    at = len(PNG_SIGNATURE)
    width = height = 0
    idat = bytearray()
    while at + 8 <= len(data):
        length, kind = struct.unpack(">I4s", data[at:at + 8])
        body = data[at + 8:at + 8 + length]
        if len(body) != length:
            raise SystemExit(f"{path}: truncated chunk {kind!r}")
        if kind == b"IHDR":
            width, height, depth, color, comp, filt, interlace = struct.unpack(">IIBBBBB", body)
            if depth != 8 or color != 6 or interlace != 0 or comp != 0 or filt != 0:
                raise SystemExit(f"{path}: only 8-bit non-interlaced RGBA is handled")
        elif kind == b"IDAT":
            idat += body
        elif kind == b"IEND":
            break
        at += 12 + length
    if not width or not height:
        raise SystemExit(f"{path}: no IHDR")
    raw = zlib.decompress(bytes(idat))
    stride = width * 4
    if len(raw) != (stride + 1) * height:
        raise SystemExit(f"{path}: unexpected decompressed size")
    out = bytearray(stride * height)
    previous = bytearray(stride)
    at = 0
    for y in range(height):
        filter_type = raw[at]
        at += 1
        line = bytearray(raw[at:at + stride])
        at += stride
        for x in range(stride):
            left = line[x - 4] if x >= 4 else 0
            up = previous[x]
            upleft = previous[x - 4] if x >= 4 else 0
            if filter_type == 1:
                line[x] = (line[x] + left) & 0xFF
            elif filter_type == 2:
                line[x] = (line[x] + up) & 0xFF
            elif filter_type == 3:
                line[x] = (line[x] + ((left + up) >> 1)) & 0xFF
            elif filter_type == 4:
                line[x] = (line[x] + _paeth(left, up, upleft)) & 0xFF
            elif filter_type != 0:
                raise SystemExit(f"{path}: unknown filter {filter_type}")
        out[y * stride:(y + 1) * stride] = line
        previous = line
    return width, height, bytes(out)


def emit(source: pathlib.Path, out: pathlib.Path, extra=()) -> int:
    images = sorted(source.glob("*.png")) + list(extra)
    if not images:
        raise SystemExit(f"no reference images under {source}")
    names = [image.stem for image in images]
    if len(set(names)) != len(names):
        raise SystemExit("ambiguous reference image basename")
    lines = [
        "/* Generated by tools/embed_cts_reference_images.py from the pinned",
        " * upstream data assets; do not edit. See that tool for why the bytes are",
        " * embedded instead of decoded at run time. */",
        "#include <cstddef>",
        "namespace ps5cts {",
        "struct ReferenceImage { const char *name; unsigned width; unsigned height;"
        " const unsigned char *pixels; };",
    ]
    entries = []
    for index, image in enumerate(images):
        width, height, pixels = decode_rgba8(image)
        payload = ",".join(str(byte) for byte in pixels)
        lines.append(f"static const unsigned char image_{index}[] = {{{payload}}};")
        entries.append(f'    {{"{image.stem}", {width}u, {height}u, image_{index}}},')
    lines += [
        "extern const ReferenceImage kGeometryReferenceImages[] = {",
        *entries,
        "};",
        "extern const unsigned kGeometryReferenceImageCount = "
        f"{len(entries)}u;",
        "}",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    return len(entries)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    parser.add_argument("--extra", action="append", default=[], type=pathlib.Path)
    args = parser.parse_args()
    count = emit(args.source, args.out, args.extra)
    print(f"[embed_cts_reference_images] embedded {count} reference images into {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
