/* Generated by tools/derive_dxvk_profile.py; do not edit. */
#ifndef PS5VK_DXVK_V262_PROFILE_H
#define PS5VK_DXVK_V262_PROFILE_H

#define DXVK262_PROFILE_ID "VP_DXVK_d3d11_level_11_0_baseline"
#define DXVK262_PROFILE_API_VERSION "1.3.204"
#define DXVK262_PROFILE_REQUIREMENT_COUNT 62u

#define DXVK262_REQUIRED_EXTENSIONS(X) \
    X("VK_EXT_robustness2", 1u) \
    X("VK_EXT_transform_feedback", 1u)

#define DXVK262_FEATURES_VK_PHYSICAL_DEVICE_FEATURES(X) \
    X(depthBiasClamp, 1u) \
    X(depthClamp, 1u) \
    X(drawIndirectFirstInstance, 1u) \
    X(dualSrcBlend, 1u) \
    X(fillModeNonSolid, 1u) \
    X(fragmentStoresAndAtomics, 1u) \
    X(fullDrawIndexUint32, 1u) \
    X(geometryShader, 1u) \
    X(imageCubeArray, 1u) \
    X(independentBlend, 1u) \
    X(multiDrawIndirect, 1u) \
    X(multiViewport, 1u) \
    X(occlusionQueryPrecise, 1u) \
    X(robustBufferAccess, 1u) \
    X(sampleRateShading, 1u) \
    X(shaderClipDistance, 1u) \
    X(shaderCullDistance, 1u) \
    X(shaderImageGatherExtended, 1u) \
    X(tessellationShader, 1u) \
    X(textureCompressionBC, 1u)

#define DXVK262_FEATURES_VK_PHYSICAL_DEVICE_ROBUSTNESS2_FEATURES_EXT(X) \
    X(nullDescriptor, 1u) \
    X(robustBufferAccess2, 1u)

#define DXVK262_FEATURES_VK_PHYSICAL_DEVICE_TRANSFORM_FEEDBACK_FEATURES_EXT(X) \
    X(geometryStreams, 1u) \
    X(transformFeedback, 1u)

#define DXVK262_FEATURES_VK_PHYSICAL_DEVICE_VULKAN11_FEATURES(X) \
    X(multiview, 1u) \
    X(shaderDrawParameters, 1u)

#define DXVK262_FEATURES_VK_PHYSICAL_DEVICE_VULKAN12_FEATURES(X) \
    X(bufferDeviceAddress, 1u) \
    X(hostQueryReset, 1u) \
    X(imagelessFramebuffer, 1u) \
    X(samplerMirrorClampToEdge, 1u) \
    X(separateDepthStencilLayouts, 1u) \
    X(shaderSubgroupExtendedTypes, 1u) \
    X(subgroupBroadcastDynamicId, 1u) \
    X(timelineSemaphore, 1u) \
    X(uniformBufferStandardLayout, 1u) \
    X(vulkanMemoryModel, 1u) \
    X(vulkanMemoryModelDeviceScope, 1u)

#define DXVK262_FEATURES_VK_PHYSICAL_DEVICE_VULKAN13_FEATURES(X) \
    X(computeFullSubgroups, 1u) \
    X(dynamicRendering, 1u) \
    X(inlineUniformBlock, 1u) \
    X(maintenance4, 1u) \
    X(pipelineCreationCacheControl, 1u) \
    X(robustImageAccess, 1u) \
    X(shaderDemoteToHelperInvocation, 1u) \
    X(shaderIntegerDotProduct, 1u) \
    X(shaderTerminateInvocation, 1u) \
    X(shaderZeroInitializeWorkgroupMemory, 1u) \
    X(subgroupSizeControl, 1u) \
    X(synchronization2, 1u)

#define DXVK262_PROPERTIES_VK_PHYSICAL_DEVICE_VULKAN11_PROPERTIES(X) \
    X(maxMultiviewInstanceIndex, UINT64_C(134217727)) \
    X(maxMultiviewViewCount, UINT64_C(6))

#define DXVK262_PROPERTIES_VK_PHYSICAL_DEVICE_VULKAN12_PROPERTIES(X) \
    X(maxTimelineSemaphoreValueDifference, UINT64_C(2147483647))

#define DXVK262_PROPERTIES_VK_PHYSICAL_DEVICE_VULKAN13_PROPERTIES(X) \
    X(maxBufferSize, UINT64_C(1073741824)) \
    X(maxDescriptorSetInlineUniformBlocks, UINT64_C(4)) \
    X(maxDescriptorSetUpdateAfterBindInlineUniformBlocks, UINT64_C(4)) \
    X(maxInlineUniformBlockSize, UINT64_C(256)) \
    X(maxInlineUniformTotalSize, UINT64_C(4)) \
    X(maxPerStageDescriptorInlineUniformBlocks, UINT64_C(4)) \
    X(maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks, UINT64_C(4))

#endif
